/**
 * IPC channel allowlist — documentation-only defense-in-depth.
 *
 * The real enforcement gate is contextIsolation:true + preload bridge.
 * This list serves as a reference and can be used by audits or future
 * middleware, but is NOT enforced at runtime in the IPC registration.
 */
export const ALLOWED_IPC_CHANNELS: readonly string[] = [
  "projects:list",
  "projects:get",
  "projects:create",
  "projects:update",
  "projects:delete",
  "sessions:start",
  "sessions:stop",
  "sessions:list",
  "sessions:get",
  "sessions:create",
  "sessions:updateStatus",
  "sessions:updateRawVideoPath",
  "sessions:delete",
  "sessions:recordActivity",
  "assets:listByProject",
  "assets:listBySession",
  "assets:listByType",
  "assets:get",
  "assets:create",
  "assets:delete",
  "settings:get",
  "settings:set",
  "settings:delete",
  "profiles:list",
  "profiles:get",
  "profiles:create",
  "profiles:update",
  "profiles:delete",
  "profiles:getPreset",
  "profiles:getSettings",
  "export:project",
  "overrides:get",
  "overrides:save",
  "overrides:clear",
  "git:repoInfo",
  "git:projectFile",
  "git:metadata",
  "git:log",
  "scanner:scan",
  "scanner:autofill",
  "feature-evidence:generate",
  "feature-evidence:list",
  "feature-evidence:get",
  "feature-evidence:save",
  "feature-evidence:update",
  "feature-evidence:accept",
  "feature-evidence:reject",
  "feature-evidence:delete",
  "ai:status",
  "ai:setConfig",
  "ai:generateDescription",
  "ai:generateScreenshotCaption",
  "ai:generatePortfolioSummary",
  "ai:clearCache",
  "portfolio:generate",
  "portfolio:data",
  "portfolio:outputDir",
  "themes:list",
  "themes:getActive",
  "themes:setActive",
  "themes:getCustomColors",
  "themes:setCustomColors",
  "deploy:zip",
  "deploy:preview",
  "deploy:run",
  "deploy:targets",
  "devserver:status",
  "devserver:start",
  "devserver:stop",
  "windows:list",
  "chapters:generate",
  "chapters:get",
  "chapters:save",
  "chapters:rename",
  "chapters:reorder",
  "chapters:delete",
  "quality:score",
  "crash-recovery:detect",
  "crash-recovery:discard",
  "crash-recovery:autoCleanup",
  "health:check",
] as const;

const ALLOWED_SET: ReadonlySet<string> = new Set(ALLOWED_IPC_CHANNELS);

export function isChannelAllowed(channel: string): boolean {
  return ALLOWED_SET.has(channel);
}

export function getAllowedChannels(): string[] {
  return [...ALLOWED_IPC_CHANNELS];
}
