import { existsSync, mkdirSync, copyFileSync, writeFileSync, readdirSync } from "fs";
import { join, basename } from "path";
import type {
  PortfolioGenerateConfig,
  PortfolioGenerateResult,
  PortfolioData,
  PortfolioProjectData,
} from "../../../../packages/shared/types/index.js";
import type { ProjectService } from "./project-service.js";
import type { SessionService } from "./session-service.js";
import type { AssetService } from "./asset-service.js";

const DEFAULT_OUTPUT_DIR = "data/portfolio";

function slugify(name: string): string {
  return name.replace(/[<>:"/\\|?*\s]+/g, "-").replace(/^-|-$/g, "").toLowerCase();
}

function escapeHtml(text: string): string {
  return text
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;");
}

function generateIndexHtml(data: PortfolioData): string {
  const projectCards = data.projects
    .map(
      (p) => `
      <div class="card">
        <h2><a href="projects/${slugify(p.name)}.html">${escapeHtml(p.name)}</a></h2>
        ${p.description ? `<p>${escapeHtml(p.description)}</p>` : ""}
        <div class="meta">
          <span class="status ${p.projectStatus}">${p.projectStatus}</span>
          ${p.techStack.length > 0 ? `<span class="tech">${escapeHtml(p.techStack.join(", "))}</span>` : ""}
        </div>
        ${p.demoPath ? `<video class="demo" src="../assets/${basename(p.demoPath)}" controls muted></video>` : ""}
        ${p.screenshots.length > 0 ? `<div class="screenshots">${p.screenshots.map((s) => `<img src="../assets/${basename(s.path)}" alt="screenshot" loading="lazy" />`).join("")}</div>` : ""}
      </div>`,
    )
    .join("\n");

  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>Portfolio</title>
  <style>
    * { margin: 0; padding: 0; box-sizing: border-box; }
    body { font-family: system-ui, sans-serif; background: #0d1117; color: #e6edf3; padding: 2rem; }
    h1 { margin-bottom: 0.5rem; }
    .summary { color: #8b949e; margin-bottom: 2rem; }
    .grid { display: grid; grid-template-columns: repeat(auto-fill, minmax(340px, 1fr)); gap: 1.5rem; }
    .card { background: #161b22; border: 1px solid #30363d; border-radius: 8px; padding: 1.25rem; }
    .card h2 { font-size: 1.1rem; margin-bottom: 0.5rem; }
    .card h2 a { color: #58a6ff; text-decoration: none; }
    .card p { color: #8b949e; font-size: 0.9rem; margin-bottom: 0.75rem; }
    .meta { display: flex; gap: 0.5rem; flex-wrap: wrap; margin-bottom: 0.75rem; }
    .status { font-size: 0.75rem; padding: 0.15rem 0.5rem; border-radius: 999px; background: #21262d; }
    .status.active { color: #3fb950; }
    .status.completed { color: #58a6ff; }
    .status.paused { color: #d29922; }
    .tech { font-size: 0.75rem; color: #8b949e; }
    .demo { width: 100%; border-radius: 4px; margin-bottom: 0.5rem; }
    .screenshots { display: flex; gap: 0.5rem; overflow-x: auto; }
    .screenshots img { height: 100px; border-radius: 4px; }
    footer { margin-top: 3rem; color: #484f58; font-size: 0.8rem; text-align: center; }
  </style>
</head>
<body>
  <h1>Portfolio</h1>
  <div class="summary">${data.summary.totalProjects} projects &middot; ${data.summary.totalSessions} sessions &middot; ${data.summary.totalScreenshots} screenshots${data.summary.hasDemos ? " &middot; demos" : ""}</div>
  <div class="grid">
${projectCards}
  </div>
  <footer>Generated by Portfolio Auto Recorder on ${data.generatedAt}</footer>
</body>
</html>`;
}

function generateProjectHtml(project: PortfolioProjectData): string {
  const featuresList =
    project.features.length > 0
      ? `<section><h2>Features</h2><ul>${project.features.map((f) => `<li>${escapeHtml(f)}</li>`).join("")}</ul></section>`
      : "";

  const techBadges =
    project.techStack.length > 0
      ? `<section><h2>Tech Stack</h2><div class="badges">${project.techStack.map((t) => `<span class="badge">${escapeHtml(t)}</span>`).join("")}</div></section>`
      : "";

  const screenshotsSection =
    project.screenshots.length > 0
      ? `<section><h2>Screenshots</h2><div class="screenshots">${project.screenshots.map((s) => `<img src="../assets/${basename(s.path)}" alt="screenshot" loading="lazy" />`).join("")}</div></section>`
      : "";

  const demoSection = project.demoPath
    ? `<section><h2>Demo</h2><video class="demo" src="../assets/${basename(project.demoPath)}" controls muted></video></section>`
    : "";

  const githubSection = project.githubUrl
    ? `<section><h2>GitHub</h2><a href="${escapeHtml(project.githubUrl)}" target="_blank">${escapeHtml(project.githubUrl)}</a></section>`
    : "";

  const sessionsSection =
    project.sessions.length > 0
      ? `<section><h2>Sessions</h2><p>${project.sessions.length} recording session${project.sessions.length === 1 ? "" : "s"}</p></section>`
      : "";

  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>${escapeHtml(project.name)} — Portfolio</title>
  <style>
    * { margin: 0; padding: 0; box-sizing: border-box; }
    body { font-family: system-ui, sans-serif; background: #0d1117; color: #e6edf3; padding: 2rem; max-width: 800px; margin: 0 auto; }
    h1 { margin-bottom: 0.5rem; }
    .back { color: #58a6ff; text-decoration: none; display: inline-block; margin-bottom: 1.5rem; }
    section { margin-bottom: 1.5rem; }
    h2 { font-size: 1rem; color: #8b949e; margin-bottom: 0.5rem; text-transform: uppercase; letter-spacing: 0.05em; }
    p, li { line-height: 1.6; }
    ul { padding-left: 1.2rem; }
    .badges { display: flex; gap: 0.4rem; flex-wrap: wrap; }
    .badge { background: #21262d; padding: 0.2rem 0.6rem; border-radius: 999px; font-size: 0.8rem; }
    .demo { width: 100%; border-radius: 4px; }
    .screenshots { display: flex; gap: 0.5rem; overflow-x: auto; }
    .screenshots img { height: 120px; border-radius: 4px; }
    a { color: #58a6ff; }
  </style>
</head>
<body>
  <a class="back" href="../index.html">&larr; Back to Portfolio</a>
  <h1>${escapeHtml(project.name)}</h1>
  ${project.description ? `<p>${escapeHtml(project.description)}</p>` : ""}
  ${demoSection}
  ${screenshotsSection}
  ${featuresList}
  ${techBadges}
  ${githubSection}
  ${sessionsSection}
</body>
</html>`;
}

export class PortfolioGeneratorImpl {
  private projectService: ProjectService;
  private sessionService: SessionService;
  private assetService: AssetService;
  private defaultOutputDir: string;
  private cachedData: PortfolioData | null = null;

  constructor(
    projectService: ProjectService,
    sessionService: SessionService,
    assetService: AssetService,
    defaultOutputDir?: string,
  ) {
    this.projectService = projectService;
    this.sessionService = sessionService;
    this.assetService = assetService;
    this.defaultOutputDir = defaultOutputDir ?? DEFAULT_OUTPUT_DIR;
  }

  async generate(config?: PortfolioGenerateConfig): Promise<PortfolioGenerateResult> {
    const outputDir = config?.outputDir ?? this.defaultOutputDir;
    const includeScreenshots = config?.includeScreenshots !== false;
    const includeDemos = config?.includeDemos !== false;

    const projects = this.projectService.list();
    const data = this.buildPortfolioData(projects, includeScreenshots, includeDemos);
    this.cachedData = data;

    const assetsDir = join(outputDir, "assets");
    const projectsDir = join(outputDir, "projects");

    if (!existsSync(outputDir)) mkdirSync(outputDir, { recursive: true });
    if (!existsSync(assetsDir)) mkdirSync(assetsDir, { recursive: true });
    if (!existsSync(projectsDir)) mkdirSync(projectsDir, { recursive: true });

    let assetCount = 0;

    for (const project of data.projects) {
      if (project.demoPath && existsSync(project.demoPath)) {
        copyFileSync(project.demoPath, join(assetsDir, basename(project.demoPath)));
        assetCount++;
      }
      for (const shot of project.screenshots) {
        if (existsSync(shot.path)) {
          copyFileSync(shot.path, join(assetsDir, basename(shot.path)));
          assetCount++;
        }
      }
    }

    writeFileSync(join(outputDir, "data.json"), JSON.stringify(data, null, 2), "utf-8");

    const indexHtml = generateIndexHtml(data);
    writeFileSync(join(outputDir, "index.html"), indexHtml, "utf-8");

    for (const project of data.projects) {
      const projectHtml = generateProjectHtml(project);
      writeFileSync(join(projectsDir, `${slugify(project.name)}.html`), projectHtml, "utf-8");
    }

    return {
      outputDir,
      projectCount: data.projects.length,
      assetCount,
      indexHtmlPath: join(outputDir, "index.html"),
      dataJsonPath: join(outputDir, "data.json"),
    };
  }

  getData(): PortfolioData {
    if (!this.cachedData) {
      const projects = this.projectService.list();
      this.cachedData = this.buildPortfolioData(projects, true, true);
    }
    return this.cachedData;
  }

  private buildPortfolioData(
    projects: ReturnType<ProjectService["list"]>,
    includeScreenshots: boolean,
    includeDemos: boolean,
  ): PortfolioData {
    const projectData: PortfolioProjectData[] = [];
    let totalSessions = 0;
    let totalScreenshots = 0;
    let hasDemos = false;

    for (const project of projects) {
      const sessions = this.sessionService.listByProject(project.id);
      const completeSessions = sessions.filter((s) => s.status === "complete");

      let demoPath: string | null = null;
      const screenshots: PortfolioProjectData["screenshots"] = [];

      if (includeDemos || includeScreenshots) {
        const assets = this.assetService.listByProject(project.id);

        if (includeDemos) {
          const demoAsset = assets.find((a) => a.type === "demo_video");
          if (demoAsset) {
            demoPath = demoAsset.path;
            hasDemos = true;
          }
        }

        if (includeScreenshots) {
          const shotAssets = assets.filter((a) => a.type === "screenshot");
          for (const shot of shotAssets) {
            screenshots.push({
              id: shot.id,
              path: shot.path,
              width: shot.width,
              height: shot.height,
            });
          }
        }
      }

      totalSessions += completeSessions.length;
      totalScreenshots += screenshots.length;

      projectData.push({
        id: project.id,
        name: project.name,
        description: project.description,
        features: project.features,
        techStack: project.techStack,
        githubUrl: project.githubUrl,
        projectStatus: project.projectStatus,
        sessions: completeSessions.map((s) => ({
          id: s.id,
          startedAt: s.startedAt,
          durationMs: s.durationMs,
          status: s.status,
        })),
        screenshots,
        demoPath,
      });
    }

    return {
      generatedAt: new Date().toISOString(),
      projects: projectData,
      summary: {
        totalProjects: projectData.length,
        totalSessions,
        totalScreenshots,
        hasDemos,
      },
    };
  }
}
